// vue/vue-objedname/src/components/Calendar/Controller/Controller.vue
<template>
  <div class="day-select-row">
    <Button @click="prevDay" class="btn" icon="fas fa-chevron-left">ss</Button>
    <!-- Tu sa budu dni generovat podla toho kolko ich chceme na stranku z DeliveryMethod -->
    <button
      v-for="day in dateArray"
      :key="day[0]"
      @click="setActive(day[0])"
      class="btn day"
      :class="{ active: day[0].getDate() === active.getDate() }"
    >
      {{ formatDateWithoutYear(day[0]) }}
      <div
        style="
           {
            display: flex;
            flex-direction: row;
          }
        "
      >
        {{ day[1] }}
        <b>
          {{ day[0].getDate() === new Date().getDate() ? "Dnes" : "" }}
        </b>
        <b>
          {{
            day[0].getDate() === new Date(Date.now() + 86400000).getDate()
              ? "Zajtra"
              : ""
          }}
        </b>
      </div>
    </button>

    <Button @click="nextDay" class="btn" icon="fas fa-chevron-right"></Button>
  </div>
</template>

<script setup lang="ts">
import { getNext10Days } from "/src/utils/helperFunctions.tsx";
import Button from "/src/components/Button/Button.vue";
import { defineProps, ref } from "vue";
import { useStore } from "vuex";
import { formatDateWithoutYear } from "../../../utils/helperFunctions";
const { setActive, active } = defineProps(["setActive", "active"]);
const store = useStore();
const startDate = ref(new Date());
// Create the dateArray using getNext10Days function
const dateArray = ref(
  getNext10Days(new Date(), store.state.value.calendarDays)
);

// Function to set the active date
const updateDateArray = () => {
  dateArray.value = getNext10Days(
    startDate.value,
    store.state.value.calendarDays
  );
};

const prevDay = () => {
  startDate.value = new Date(startDate.value);
  startDate.value.setDate(startDate.value.getDate() - 1);
  updateDateArray();

  setActive(startDate.value);
};

const nextDay = () => {
  startDate.value = new Date(startDate.value);
  startDate.value.setDate(startDate.value.getDate() + 1);
  updateDateArray();
  setActive(startDate.value);
};
</script>

<style>
/* Add your Calendar.scss styles here */
/* Define .active class styles for the active button */
.active {
  /* Add your active button styles here */
}
</style>

// react/react-objedname/src/components/Calendar/Controller/Controller.tsx
import React, { useState, useEffect } from "react";
import "../Calendar.scss";
import Button from "../../Button/Button";
import { MdArrowForwardIos, MdArrowBackIos } from "react-icons/md";
import { getNext10Days, isToday } from "/src/utils/helperFunctions.tsx";
import { useSelector } from "react-redux";
import { current } from "@reduxjs/toolkit";

const handleActive = () => {};

function Controller(props) {
  const calendarDays = useSelector((state) => state.value.calendarDays);

  const [startDate, setStartDate] = useState(new Date());
  const [dateArray, setDateArray] = useState(
    getNext10Days(startDate, calendarDays)
  );
  useEffect(() => {
    setDateArray(getNext10Days(startDate, calendarDays));
  }, [calendarDays, startDate]);

  const prevDay = () => {
    const prevDate = new Date(startDate);
    prevDate.setDate(prevDate.getDate() - 1);
    return prevDate;
  };

  const nextDay = () => {
    const nextDate = new Date(startDate);
    nextDate.setDate(nextDate.getDate() + 1);
    return nextDate;
  };

  return (
    <div className="day-select-row">
      <Button
        onClick={() => {
          props.setActive(prevDay);
          setStartDate(prevDay);
        }}
        icon={<MdArrowBackIos />}
        className="btn"
      />
      {/* Tu sa budu dni generovat podla toho kolko ich chceme na stranku z DeliveryMethod */}
      {dateArray.map((day, index) => (
        <>
          <Button
            onClick={() => {
              props.setActive(day[0]);
            }}
            active={day[0].getDate() === props.active.getDate()}
            text={`${day[0].toLocaleDateString("sk-SK")} ${day[1]}`}
          />
        </>
      ))}

      <Button
        onClick={() => {
          props.setActive(nextDay);
          setStartDate(nextDay);
        }}
        icon={<MdArrowForwardIos />}
        className="btn"
      />
    </div>
  );
}

export default Controller;
