// react/react-objedname/src/components/Calendar/Cell/Cell.tsx
import React from "react";
import "../Calendar.scss";

interface CellProps {
  time: string;
  capacity: number;
  onClick?: () => void;
  active: boolean;
  originalCapacity: number;
}

function Cell(props: CellProps) {
  const isValidTimeFormat = (time) => {
    // Regular expression to check for format "HH:mm" (e.g., "14:00")
    const timeRegex = /^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$/;
    return timeRegex.test(time);
  };

  if (!isValidTimeFormat(props.time)) {
    // Handle the case when the time format is incorrect
    return <div className="error">Invalid time format</div>;
  }

  return (
    <div
      onClick={props.onClick}
      style={{ backgroundColor: props.active ? "red" : "" }}
      className={`time-select`}
    >
      {props.time}
      <span className="availability">
        ({props.capacity}/{props.originalCapacity})
      </span>
    </div>
  );
}

export default Cell;

// vue/vue-objedname/src/components/Calendar/Cell/Cell.vue
<template>
  <div
    @click="handleClick"
    :style="{}"
    class="time-select"
    :class="{
      active: !(props.capacity >= props.originalCapacity) && active,
      disabled: props.capacity >= props.originalCapacity,
    }"
  >
    {{ time }}
    <span class="availability"> ({{ capacity }}/{{ originalCapacity }}) </span>
  </div>
  <modal
    v-if="showModal"
    @close="showModal = false"
    :time="time"
    :capacity="capacity"
    :originalCapacity="originalCapacity"
    :isSucces="false"
    :setShowSuccessModal="() => (showSuccessModal = true)"
  >
  </modal>
  <modal
    v-if="showSuccessModal"
    @closeSuccess="showSuccessModal = false"
    :isSucces="true"
  >
  </modal>
</template>

<script setup lang="ts">
import { defineProps, ref } from "vue";
import Modal from "../Modal/Modal.vue";
import { isValidTimeFormat } from "/src/utils/helperFunctions.tsx";
const showModal = ref(false);
const showSuccessModal = ref(false);
const props = defineProps({
  time: String,
  capacity: Number,
  onClick: Function,
  active: Boolean,
  originalCapacity: Number,
});

const handleClick = () => {
  if (!isValidTimeFormat(props.time)) {
    // Handle the case when the time format is incorrect
    console.error("Invalid time format");
    return;
  }
  if (props.onClick) {
    showModal.value = true;
    props.onClick();
  }
};
</script>

<style lang="scss" scoped>
.time-select {
  cursor: pointer;
}
.active {
  background-color: #85bb36;
}
.disabled {
  backdrop-filter: blur(2px);
  backdrop-filter: brightness(50%);
  border-color: black;
  color: gray;
  cursor: not-allowed;
}

/* Add the styles from "Calendar.scss" here */
</style>
